import joblib
import os
import zipfile
import warnings
from pathlib import Path
import shutil
from copy import deepcopy
from amp.base import BaseModel


def forecast_feature(model, targets, lead_time, forecast_len, lags=[], include_future=True):
    features = {}
    for target in targets:
        for i in range(lead_time, lead_time + forecast_len):
            windows = []
            for lag in lags:
                windows.append((-lag+i, -lag+i))

            if include_future:
                windows.append((i, i))

            tmp_feature = {'windows': windows,
                           'type': 'numeric'}
            features[f'{model}_{target}_forecast_{i}'] = tmp_feature

    return features


class Pipeline(BaseModel):

    def __init__(self, models={}, output_map='last'):
        """

        Parameters
        ----------
        models : dict
            Dict of amp.BaseModel objects with model name as the key.
        output_map : str or dict, default='last'
            Specifies outputs of the model. The parameter accepts either a name of the model (str) in which case
            the Pipeline outputs are all the outputs of the specified model. It is also possible to specify the outputs
            explicitly with a dict where key is in format {model_name}_{output} and the value specifies the output
            produced by the Pipeline. This format is needed in the case the Pipeline should produce outputs from several
            models.'
        """
        # models are stored in a dictionary
        self._models = models
        if isinstance(output_map, str):
            if output_map == 'last':
                model_name = list(self._models.keys())[-1]
            else:
                model_name = output_map
            model = self._models[model_name]
            self._output_map = {f'{model_name}_{output}': output for output in model.outputs}
        else:
            self._output_map = output_map
        self._features = {}
        self._outputs = list(self._output_map.values())
        self._update_fparam()

    def _update_fparam(self):
        if len(self._models) > 0:
            model_name = next(iter(self._models))
            model = self._models[model_name]
            self.forecast_len = model.forecast_len
            self.lead_time = model.lead_time
            self._features = self._join_features()
        else:
            self._flen = None
            self._features = {}

    def _join_features(self):
        """ Forms a common feature set for all models.

        This is required for online use of the Pipeline to provide the information about the model inputs
        that needs to be provided.

        TODO: Contains a bug where features including past and future values are fully dropped. Should only drop the
         future part.

        Returns
        -------

        """
        features = {}

        # Collect the outputs of all models. This is needed to remove features that are produced by other models and
        # Don't need to be fetched from outside.
        m_outputs = [f'{name}_{output}' for name, model in self._models.items() for output in model.outputs]

        # Add the periods as separate (columns)
        model_outputs = []
        for output in m_outputs:
            model_outputs += [f'{output}_forecast_{i}' for i in range(self.lead_time, self.forecast_len)]

        for name, model in self._models.items():
            for fname, value in model.features.items():

                # Don't add the feature if it is generated by another internal model.
                # This is the case if the feature requires future values and is the same as an output of another model.
                # Todo: a more robust check would be to compare the outputs and features and if the windows
                #  match then remove the feature form the list.
                if model.feature_window(fname)[1] > 0 and fname in model_outputs:
                    continue

                # Remove 'heating_total' features that is a latent variable of the model.
                if fname == 'heating_total':
                    continue

                if fname in features.keys():
                    if value['windows'] not in features[fname]['windows']:
                        features[fname]['windows'] += value['windows']
                        # Remove duplicates
                        features[fname]['windows'] = list(set(features[fname]['windows']))

                else:
                    features[fname] = deepcopy(value)

        return features

    # todo think whether this can be somehow supported. Now difficult because of the output map.
    #def add_model(self, name, model):
    #    self._models[name] = model
    #    self._update_fparam()

    def _single_predict(self, df):
        pred_dict = self._target_predict(df)

        forecast = None
        for output, pred in pred_dict.items():
            if pred.count(axis='columns').any() > 1:
                raise ValueError('Forecast has overlapping values. Cannot produce single output')

            # Select the only value.
            pred[output] = pred.max(axis=1)
            if forecast is None:
                forecast = pred[[output]].copy()
            else:
                forecast[output] = pred[output]

        return forecast

    def _target_predict(self, df):
        input_df = df.copy()
        output_dict = {}

        for name, model in self._models.items():
            pred_dict = model.predict(input_df, output_mode='target')

            # copy the predictions into the input so that it can be used by the following model.
            for output, pred in pred_dict.items():
                columns = [f'{name}_{output}_{col}' for col in pred.columns]
                tmp_index = input_df.index.intersection(pred.index)
                input_df.loc[tmp_index, columns] = pred.loc[tmp_index, pred.columns].values

                output_name = self._output_map.get(f'{name}_{output}')
                if output_name is not None:
                    output_dict[output_name] = pred

        return output_dict

    def predict(self, input_df, output_mode='target'):

        if output_mode == 'single':
            pred = self._single_predict(input_df)
        elif output_mode == 'target':
            pred = self._target_predict(input_df)
        else:
            raise ValueError(f'Invalid output mode: {output_mode}')

        return pred

    def fit(self, df):
        input_df = df.copy()
        for name, model in self._models.items():

            model.fit(input_df)
            # todo how to divide the df so that the resulst do not overfit. Lets just accept the overfitting for now
            #  and think alternative solutions later.

            pred_dict = model.predict(input_df, output_mode='target')

            # copy the predictions into the input so that it can be used by the following model.
            for output, pred in pred_dict.items():
                columns = [f'{name}_{output}_{col}' for col in pred.columns]
                tmp_index = input_df.index.intersection(pred.index)
                input_df.loc[tmp_index, columns] = pred.loc[tmp_index, pred.columns].values

    def save(self, filename):
        if str(filename)[-4:] != '.zip':
            warnings.warn('Invalid file format for the model. Only zip supported.')
            filename = str(filename) + '.zip'

        model_files = {}
        models_tmp = deepcopy(self._models)

        # Save the individual models
        for m_name, model in self._models.items():
            model_file = f'{str(filename)[:-4]}_{m_name}_model.zip'
            model.save(model_file)
            model_files[f'{m_name}_model.zip'] = model_file
            # In order to save the Pipeline, the models need to be removed as they might contain non pickable parts.
            self._models[m_name] = type(model)

        #self._models = {}
        pickle_file = f'{str(filename)[:-4]}.pkl'
        joblib.dump(self, pickle_file)
        model_files['main.pkl'] = pickle_file
        self._models = models_tmp

        # Add all files to a zip file.
        with zipfile.ZipFile(filename, 'w') as zip_file:
            for name, m_file in model_files.items():
                zip_file.write(m_file, arcname=name)

        # Remove the original files.
        for m_file in model_files.values():
            os.remove(m_file)

    @classmethod
    def load(self, filename):
        if str(filename)[-4:] != '.zip':
            warnings.warn('Invalid file format for the model. Only zip supported.')
            filename = str(filename) + '.zip'

        extracted_dir = Path(filename).parent.joinpath('extracted_files')

        # Extract the contents of the zip file
        with zipfile.ZipFile(filename, 'r') as zip_file:
            zip_file.extractall(extracted_dir)

        # Load the Forecaster object.
        pipeline = joblib.load(extracted_dir.joinpath('main.pkl'))

        # Load individual
        for m_name, model_type in pipeline._models.items():
            pipeline._models[m_name] = model_type.load(extracted_dir.joinpath(f'{m_name}_model.zip'))

        # Remove the extracted files.
        shutil.rmtree(extracted_dir)

        return pipeline
