"""
Piece-wise Linear Kalman Filter with neural network parameterized matrices.

The matrices A, B, C, E are generated by a single neural network based on disturbances.

State space model:
    x[t+1] = A(d[t]) @ x[t] + B(d[t]) @ u[t] + E(d[t]) @ d[t] + b_x + w[t]
    y[t] = C(d[t]) @ x[t] + b_y + v[t]

where:
    x[t] - latent state vector
    u[t] - control inputs (controllable)
    d[t] - disturbance inputs (uncontrollable)
    y[t] - observations/outputs
    w[t] ~ N(0, Q) - process noise
    v[t] ~ N(0, R) - measurement noise
    
    A(d[t]) - state transition matrix (NN-generated, time-varying)
    B(d[t]) - control influence matrix (NN-generated, time-varying)
    C(d[t]) - observation matrix (NN-generated, time-varying)
    E(d[t]) - disturbance influence matrix (NN-generated, time-varying)
    b_x - state bias vector (trainable, optional)
    b_y - observation bias vector (trainable, optional)

Key differences from standard LKF:
- Matrices are functions of disturbances: A(d[t]), B(d[t]), C(d[t]), E(d[t])
- Single MLP generates all matrices simultaneously from d[t]
- No warmup stages - NN trains from the start
"""

import torch
import torch.nn as nn
from amp.torch.models.lkf import TorchLinearDynamicsWithKF, BatchedLinearKalmanFilter


class PWLKF(TorchLinearDynamicsWithKF):
    """
    Piece-wise Linear Kalman Filter with NN-parameterized matrices.
    
    Key feature:
    - Matrices A, B, C, E are generated by a single neural network based on current disturbances
    - Single MLP: [A, B, C, E] = matrix_generator(d[t])
    
    State space model:
        x[t+1] = A(d[t]) @ x[t] + B(d[t]) @ u[t] + E(d[t]) @ d[t] + b_x + w[t]
        y[t] = C(d[t]) @ x[t] + b_y + v[t]
    
    Training:
    - NN trains from the start (no warmup stages)
    - Matrices are generated dynamically at each timestep
    - More parameter efficient than separate MLPs per matrix
    - Optional bias vectors b_x and b_y can be enabled independently
    """
    
    def __init__(
        self,
        control_features: list,
        disturbance_features: list = None,
        latent_dim: int = 3,
        observation_features: list = None,
        target_features: list = None,
        output_dim: int = 1,
        process_noise_cov: float = 1e-3,
        measurement_noise_cov: float = 1e-2,
        learnable_noise: bool = True,
        noise_constraint_type: str = 'diagonal_positive',
        learning_rate: float = 1e-3,
        num_encoding_measurements: int = 1,
        # NN parameters
        nn_hidden_dims: list = None,
        nn_activation: str = 'relu',
        # Piecewise configuration
        dynamic_matrices: list = None,
        # Bias vectors
        use_state_bias: bool = True,
        use_observation_bias: bool = True,
        **kwargs
    ):
        """
        Args:
            control_features: List of control input feature names
            disturbance_features: List of disturbance feature names (REQUIRED for NN input)
            latent_dim: Dimension of latent state
            observation_features: List of measurement feature names
            target_features: List of target feature names
            output_dim: Dimension of observations/targets
            process_noise_cov: Initial process noise covariance
            measurement_noise_cov: Initial measurement noise covariance
            learnable_noise: If True, learn Q and R during training
            noise_constraint_type: Type of constraint for learnable noise covariances.
                                  Options: 'cholesky', 'diagonal_positive', 'none'
            learning_rate: Learning rate for optimizer
            num_encoding_measurements: Number of recent measurements to use for encoding
            nn_hidden_dims: Hidden layer dimensions for MLPs.
                           Default: [2*latent_dim, 2*latent_dim]
            nn_activation: Activation function ('relu', 'tanh', 'elu')
            dynamic_matrices: List of matrix names to make piecewise linear.
                               Options: ['A', 'B', 'C', 'E']
                               If None (default), all matrices are piecewise (current behavior).
                               If empty list [], all matrices are static learnable parameters.
                               Example: ['A', 'E'] makes A and E piecewise, B and C static.
            use_state_bias: If True, add learnable bias term b_x to state dynamics
            use_observation_bias: If True, add learnable bias term b_y to observations
            **kwargs: Additional arguments passed to parent class
        """
        # Extract matrix_generation_features if present (handled by child classes, not parent)
        matrix_generation_features = kwargs.pop('matrix_generation_features', None)
        
        # Initialize parent class
        super().__init__(
            control_features=control_features,
            disturbance_features=disturbance_features,
            latent_dim=latent_dim,
            observation_features=observation_features,
            target_features=target_features,
            output_dim=output_dim,
            process_noise_cov=process_noise_cov,
            measurement_noise_cov=measurement_noise_cov,
            learnable_noise=learnable_noise,
            noise_constraint_type=noise_constraint_type,
            learning_rate=learning_rate,
            num_encoding_measurements=num_encoding_measurements,
            use_state_bias=use_state_bias,
            use_observation_bias=use_observation_bias,
            **kwargs
        )
        
        # Store matrix_generation_features (for now, same as disturbances for backward compatibility)
        # This will be properly utilized once the data pipeline supports separate matrix gen features
        self.matrix_generation_features = matrix_generation_features or disturbance_features
        
        # Default: all matrices are piecewise (backward compatible)
        if dynamic_matrices is None:
            dynamic_matrices = ['A', 'B', 'C', 'E']
        
        # Validate dynamic_matrices
        valid_matrices = {'A', 'B', 'C', 'E'}
        invalid = set(dynamic_matrices) - valid_matrices
        if invalid:
            raise ValueError(
                f"Invalid matrix names in dynamic_matrices: {invalid}. "
                f"Valid options: {valid_matrices}"
            )
        
        self.dynamic_matrices = dynamic_matrices
        
        # Check that disturbances are provided if any matrix is piecewise
        if len(dynamic_matrices) > 0 and not self.has_disturbances:
            raise ValueError(
                f"PWLKF with dynamic matrices {dynamic_matrices} requires "
                f"disturbance_features for matrix generation. Provide disturbance_features argument."
            )
        
        # Replace LinearKalmanFilter with BatchedLinearKalmanFilter
        # to support time-varying (batched) C matrices
        self.kf = BatchedLinearKalmanFilter(
            state_dim=latent_dim,
            input_dim=self.control_dim,
            output_dim=self.measurement_dim,
            process_noise_cov=process_noise_cov,
            measurement_noise_cov=measurement_noise_cov,
            learnable_noise=learnable_noise,
            noise_constraint_type=noise_constraint_type,
        )
        
        # Default hidden dimensions: 2x latent_dim for each layer
        if nn_hidden_dims is None:
            nn_hidden_dims = [2 * latent_dim, 2 * latent_dim]
        
        # Get activation function
        activation_fn = {
            'relu': nn.ReLU,
            'tanh': nn.Tanh,
            'elu': nn.ELU
        }.get(nn_activation.lower(), nn.ReLU)
        
        # Store configuration
        self.nn_hidden_dims = nn_hidden_dims
        self.nn_activation = nn_activation
        
        # Calculate sizes for each matrix
        self.A_size = latent_dim * latent_dim
        self.B_size = latent_dim * self.control_dim
        self.C_size = self.measurement_dim * latent_dim
        self.E_size = latent_dim * self.disturbance_dim
        
        # Create matrix generators and static parameters
        self.matrix_generators = nn.ModuleDict()
        self.static_matrices = nn.ParameterDict()
        
        matrix_configs = {
            'A': (self.A_size, (latent_dim, latent_dim)),
            'B': (self.B_size, (latent_dim, self.control_dim)),
            'C': (self.C_size, (self.measurement_dim, latent_dim)),
            'E': (self.E_size, (latent_dim, self.disturbance_dim)),
        }
        
        for matrix_name, (flat_size, shape) in matrix_configs.items():
            if matrix_name in dynamic_matrices:
                # Create MLP for dynamic matrix
                self.matrix_generators[matrix_name] = self._build_mlp(
                    input_dim=self.disturbance_dim,
                    output_dim=flat_size,
                    hidden_dims=nn_hidden_dims,
                    activation_fn=activation_fn
                )
            else:
                # Create static learnable parameter
                static_matrix = torch.randn(*shape) * 0.01
                # Initialize with small values similar to parent initialization
                if matrix_name == 'A':
                    # A close to identity for stability
                    static_matrix = torch.eye(latent_dim) * 0.9 + torch.randn(latent_dim, latent_dim) * 0.01
                elif matrix_name == 'C':
                    # C initialized with small random values
                    static_matrix = torch.randn(*shape) * 0.1
                
                self.static_matrices[matrix_name] = nn.Parameter(static_matrix)
        
        # Update hyperparameters
        self.save_hyperparameters()
    
    def _build_mlp(self, input_dim: int, output_dim: int, hidden_dims: list, activation_fn):
        """
        Build an MLP for matrix generation.
        
        Args:
            input_dim: Input dimension (disturbance_dim)
            output_dim: Output dimension (flattened matrix size)
            hidden_dims: List of hidden layer dimensions
            activation_fn: Activation function class
            
        Returns:
            nn.Sequential: MLP module
        """
        layers = []
        current_dim = input_dim
        
        # Hidden layers with activation
        for hidden_dim in hidden_dims:
            layers.append(nn.Linear(current_dim, hidden_dim))
            layers.append(activation_fn())
            current_dim = hidden_dim
        
        # Output layer (no activation)
        layers.append(nn.Linear(current_dim, output_dim))
        
        mlp = nn.Sequential(*layers)
        
        # Initialize with small weights similar to parent class
        for layer in mlp:
            if isinstance(layer, nn.Linear):
                # Use small initialization similar to parent's 0.01 and 0.1 factors
                nn.init.xavier_uniform_(layer.weight, gain=0.1)
                nn.init.zeros_(layer.bias)
        
        return mlp
    
    def _generate_matrices(self, d_t):
        """
        Generate state-space matrices from disturbances.
        
        dynamic matrices are generated by MLPs based on disturbances.
        Static matrices are replicated across the batch to maintain batched interface.
        
        Args:
            d_t: Disturbances at time t (batch_size, disturbance_dim)
            
        Returns:
            A: State transition matrix (batch_size, latent_dim, latent_dim)
            B: Control matrix (batch_size, latent_dim, control_dim)
            C: Observation matrix (batch_size, measurement_dim, latent_dim)
            E: Disturbance matrix (batch_size, latent_dim, disturbance_dim)
        """
        batch_size = d_t.shape[0]
        
        matrices = {}
        matrix_shapes = {
            'A': (self.latent_dim, self.latent_dim),
            'B': (self.latent_dim, self.control_dim),
            'C': (self.measurement_dim, self.latent_dim),
            'E': (self.latent_dim, self.disturbance_dim),
        }
        
        for matrix_name, shape in matrix_shapes.items():
            if matrix_name in self.matrix_generators:
                # Generate from disturbances using MLP
                flat_matrix = self.matrix_generators[matrix_name](d_t)
                matrices[matrix_name] = flat_matrix.view(batch_size, *shape)
            else:
                # Replicate static parameter across batch
                matrices[matrix_name] = self.static_matrices[matrix_name].unsqueeze(0).expand(
                    batch_size, -1, -1
                )
        
        return matrices['A'], matrices['B'], matrices['C'], matrices['E']
    
    def _compute_state_mean(self, x_mean, u_t, A, B, d_t=None, E=None):
        """
        Compute predicted state mean with time-varying (batched) matrices.
        
        Override parent method to handle batched matrices from NN generation.
        
        x[t+1] = A(d[t]) @ x[t] + B(d[t]) @ u[t] + E(d[t]) @ d[t] + b_x
        
        Args:
            x_mean: Current state mean (batch, latent_dim)
            u_t: Control input at time t (batch, control_dim)
            A: State transition matrix (batch, latent_dim, latent_dim) - batched!
            B: Control matrix (batch, latent_dim, control_dim) - batched!
            d_t: Disturbance input at time t (batch, disturbance_dim) - optional
            E: Disturbance matrix (batch, latent_dim, disturbance_dim) - batched!
            
        Returns:
            x_mean_pred: Predicted state mean (batch, latent_dim)
        """
        # For batched matrices, use batch matrix multiplication
        # x_mean: (batch, latent_dim) -> (batch, latent_dim, 1)
        # A: (batch, latent_dim, latent_dim)
        # Result: (batch, latent_dim, 1) -> (batch, latent_dim)
        x_mean_pred = (A @ x_mean.unsqueeze(-1)).squeeze(-1)
        x_mean_pred = x_mean_pred + (B @ u_t.unsqueeze(-1)).squeeze(-1)
        
        if d_t is not None and E is not None:
            x_mean_pred = x_mean_pred + (E @ d_t.unsqueeze(-1)).squeeze(-1)
        
        # State bias (broadcasting handles batch dimension automatically)
        x_mean_pred = x_mean_pred + self.b_x
        
        return x_mean_pred
    
    def _compute_state_covariance(self, x_cov, A):
        """
        Compute predicted state covariance with time-varying (batched) matrices.
        
        Override parent method to handle batched A matrix from NN generation.
        
        P[t+1] = A(d[t]) @ P[t] @ A(d[t]).T + Q
        
        Args:
            x_cov: Current state covariance (batch, latent_dim, latent_dim)
            A: State transition matrix (batch, latent_dim, latent_dim) - batched!
            
        Returns:
            x_cov_pred: Predicted state covariance (batch, latent_dim, latent_dim)
        """
        # For batched matrices: A @ x_cov @ A.T
        # A: (batch, latent_dim, latent_dim)
        # x_cov: (batch, latent_dim, latent_dim)
        # A.transpose(-2, -1): transpose last two dimensions
        x_cov_pred = A @ x_cov @ A.transpose(-2, -1) + self.Q.unsqueeze(0)
        return x_cov_pred
    
    def _compute_observation(self, x_mean, C, project_to_targets=False):
        """
        Compute observation from state with time-varying (batched) C matrix.
        
        Override parent method to handle batched C matrix from NN generation.
        
        y = C(d[t]) @ x + b_y
        
        Args:
            x_mean: State mean (batch, latent_dim)
            C: Observation matrix (batch, measurement_dim, latent_dim) - batched!
            project_to_targets: If True and target_indices exist, project to target subset
            
        Returns:
            y_pred: Predicted observation (batch, measurement_dim) or (batch, output_dim)
        """
        # For batched C: use batch matrix multiplication
        # x_mean: (batch, latent_dim) -> (batch, latent_dim, 1)
        # C: (batch, measurement_dim, latent_dim)
        # Result: (batch, measurement_dim, 1) -> (batch, measurement_dim)
        y_pred = (C @ x_mean.unsqueeze(-1)).squeeze(-1)
        
        # Add observation bias (broadcasting handles batch dimension automatically)
        y_pred = y_pred + self.b_y
        
        # Project to targets if requested and mapping exists
        if project_to_targets and self.target_indices is not None:
            y_pred = y_pred[:, self.target_indices]  # (batch, output_dim)
        
        return y_pred
    
    def _compute_observation_uncertainty(self, x_cov, C, R_diag, project_to_targets=False):
        """
        Compute observation uncertainty with time-varying (batched) C matrix.
        
        Override parent method to handle batched C matrix from NN generation.
        
        Var(y) = C(d[t]) @ Cov(x) @ C(d[t]).T + R
        std(y) = sqrt(Var(y))
        
        Args:
            x_cov: State covariance (batch, latent_dim, latent_dim)
            C: Observation matrix (batch, measurement_dim, latent_dim) - batched!
            R_diag: Diagonal of measurement noise covariance (1, measurement_dim)
            project_to_targets: If True and target_indices exist, project to target subset
            
        Returns:
            y_std: Observation standard deviation (batch, measurement_dim) or (batch, output_dim)
        """
        # For batched C: C @ x_cov @ C.T
        # C: (batch, measurement_dim, latent_dim)
        # x_cov: (batch, latent_dim, latent_dim)
        # C.transpose(-2, -1): (batch, latent_dim, measurement_dim)
        C_x_cov = C @ x_cov  # (batch, measurement_dim, latent_dim)
        y_var = (C_x_cov * C).sum(dim=-1) + R_diag  # (batch, measurement_dim)
        
        # Project to targets if requested and mapping exists
        if project_to_targets and self.target_indices is not None:
            y_var = y_var[:, self.target_indices]  # (batch, output_dim)
        
        y_std = torch.sqrt(y_var)
        return y_std
    
    def encode_with_kf(self, control_inputs, measurements, disturbance_inputs=None, 
                       matrix_generation_features=None, **kwargs):
        """
        Encode initial state using Kalman filter with measurements.
        
        Different from parent: generates time-varying matrices A(d[t]), B(d[t]), C(d[t]), E(d[t])
        at each timestep based on disturbances (for dynamic matrices).
        
        Args:
            control_inputs: Historical control inputs (batch, control_dim, window)
            measurements: Historical observations (batch, output_dim, window)
            disturbance_inputs: Historical disturbances (batch, disturbance_dim, window)
                               Required if any matrix is piecewise
            matrix_generation_features: Alternative features for matrix generation (batch, feature_dim, window)
                                       If None, uses disturbance_inputs
            **kwargs: Additional model-specific parameters (unused, for interface compatibility)
            
        Returns:
            x_mean: Estimated initial state mean (batch, latent_dim)
            x_cov: Estimated initial state covariance (batch, latent_dim, latent_dim)
        """
        # Use matrix_generation_features if provided, else fall back to disturbance_inputs
        mgf = matrix_generation_features if matrix_generation_features is not None else disturbance_inputs
        
        if len(self.dynamic_matrices) > 0 and mgf is None:
            raise ValueError(
                f"PWLKF with dynamic matrices {self.dynamic_matrices} requires "
                f"either disturbance_inputs or matrix_generation_features for encode_with_kf"
            )
        
        batch_size = control_inputs.shape[0]
        window_size = control_inputs.shape[-1]
        device = control_inputs.device
        
        # Initialize state with zero mean and learnable covariance
        x_mean = torch.zeros(batch_size, self.latent_dim, device=device)
        x_cov = self.kf.P0.unsqueeze(0).expand(batch_size, -1, -1).clone()
        x_mean_traj = []
        x_cov_traj = []
        
        # Pre-expand fixed matrices
        R_expanded = self.R.unsqueeze(0).expand(batch_size, -1, -1)
        I_expanded = torch.eye(self.latent_dim, device=device).unsqueeze(0).expand(batch_size, -1, -1)
        
        # For all-static matrices, create dummy features for matrix generation
        if len(self.dynamic_matrices) == 0 and mgf is None:
            mgf = torch.zeros(batch_size, 1, window_size, device=device)
        
        # Determine how many measurements to use
        if self.num_encoding_measurements == 1:
            # SIMPLIFIED: Use only the LAST measurement (fastest)
            mg_last = mgf[:, :, -1]  # (batch, feature_dim)
            A_last, B_last, C_last, E_last = self._generate_matrices(mg_last)
            
            y_last = measurements[:, :, -1]  # (batch, output_dim)
            x_mean, x_cov = self.kf.update(x_mean, x_cov, y_last, C_last,
                                          C_expanded=C_last, R_expanded=R_expanded, I_expanded=I_expanded)
            x_mean_traj.append(x_mean)
            x_cov_traj.append(x_cov)
        
        elif self.num_encoding_measurements == -1:
            # FULL: Use ALL measurements with sequential filtering (most accurate)
            for t in range(window_size):
                u_t = control_inputs[:, :, t]  # (batch, control_dim)
                y_t = measurements[:, :, t]    # (batch, output_dim)
                d_t = disturbance_inputs[:, :, t] if disturbance_inputs is not None else None  # (batch, disturbance_dim)
                mg_t = mgf[:, :, t]  # (batch, feature_dim)
                
                # Generate time-varying matrices based on matrix generation features
                A_t, B_t, C_t, E_t = self._generate_matrices(mg_t)
                
                # Predict state with time-varying dynamics
                x_mean_pred = self._compute_state_mean(x_mean, u_t, A_t, B_t, d_t, E_t)
                x_cov_pred = self._compute_state_covariance(x_cov, A_t)
                
                # Update with measurement using time-varying observation model
                x_mean, x_cov = self.kf.update(x_mean_pred, x_cov_pred, y_t, C_t,
                                              C_expanded=C_t, R_expanded=R_expanded, I_expanded=I_expanded)
                x_mean_traj.append(x_mean)
                x_cov_traj.append(x_cov)
        
        else:
            # PARTIAL: Use last N measurements with sequential filtering
            num_steps = min(self.num_encoding_measurements, window_size)
            start_idx = window_size - num_steps
            
            for t in range(start_idx, window_size):
                u_t = control_inputs[:, :, t]  # (batch, control_dim)
                y_t = measurements[:, :, t]    # (batch, output_dim)
                d_t = disturbance_inputs[:, :, t] if disturbance_inputs is not None else None  # (batch, disturbance_dim)
                mg_t = mgf[:, :, t]  # (batch, feature_dim)
                
                # Generate time-varying matrices based on matrix generation features
                A_t, B_t, C_t, E_t = self._generate_matrices(mg_t)
                
                # Predict state with time-varying dynamics
                x_mean_pred = self._compute_state_mean(x_mean, u_t, A_t, B_t, d_t, E_t)
                x_cov_pred = self._compute_state_covariance(x_cov, A_t)
                
                # Update with measurement using time-varying observation model
                x_mean, x_cov = self.kf.update(x_mean_pred, x_cov_pred, y_t, C_t,
                                              C_expanded=C_t, R_expanded=R_expanded, I_expanded=I_expanded)
                x_mean_traj.append(x_mean)
                x_cov_traj.append(x_cov)
        
        return torch.stack(x_mean_traj, dim=-1), torch.stack(x_cov_traj, dim=-1)
    
    def predict_with_kf(self, x_mean, x_cov, control_inputs, disturbance_inputs=None, 
                        matrix_generation_features=None, **kwargs):
        """
        Predict forward using Kalman filter without measurements.
        
        Different from parent: generates time-varying matrices A(d[t]), B(d[t]), C(d[t]), E(d[t])
        at each timestep based on disturbances (for dynamic matrices).
        
        Args:
            x_mean: Initial state mean (batch, latent_dim)
            x_cov: Initial state covariance (batch, latent_dim, latent_dim)
            control_inputs: Control inputs (batch, control_dim, time_steps)
            disturbance_inputs: Disturbance inputs (batch, disturbance_dim, time_steps)
                               Required if any matrix is piecewise
            matrix_generation_features: Alternative features for matrix generation (batch, feature_dim, time_steps)
                                       If None, uses disturbance_inputs
            **kwargs: Additional model-specific parameters (unused, for interface compatibility)
            
        Returns:
            predictions: Predicted outputs (batch, output_dim, time_steps)
            uncertainties: Prediction uncertainties (batch, output_dim, time_steps)
        """
        # Use matrix_generation_features if provided, else fall back to disturbance_inputs
        mgf = matrix_generation_features if matrix_generation_features is not None else disturbance_inputs
        
        if len(self.dynamic_matrices) > 0 and mgf is None:
            raise ValueError(
                f"PWLKF with dynamic matrices {self.dynamic_matrices} requires "
                f"either disturbance_inputs or matrix_generation_features for predict_with_kf"
            )
        
        batch_size = control_inputs.shape[0]
        time_steps = control_inputs.shape[-1]
        device = control_inputs.device
        
        # For all-static matrices, create dummy features for matrix generation
        if len(self.dynamic_matrices) == 0 and mgf is None:
            mgf = torch.zeros(batch_size, 1, time_steps, device=device)
        
        # R diagonal for uncertainty computation
        R_diag = torch.diagonal(self.R, dim1=0, dim2=1).unsqueeze(0)  # (1, output_dim)
        
        predictions = []
        uncertainties = []
        
        for t in range(time_steps):
            u_t = control_inputs[:, :, t]  # (batch, control_dim)
            d_t = disturbance_inputs[:, :, t] if disturbance_inputs is not None else None  # (batch, disturbance_dim)
            mg_t = mgf[:, :, t]  # (batch, feature_dim)
            
            # Generate time-varying matrices based on matrix generation features
            A_t, B_t, C_t, E_t = self._generate_matrices(mg_t)
            
            # Predict next state with time-varying dynamics
            x_mean = self._compute_state_mean(x_mean, u_t, A_t, B_t, d_t, E_t)
            x_cov = self._compute_state_covariance(x_cov, A_t)
            
            # Predict observation using time-varying observation model (project to targets)
            y_pred = self._compute_observation(x_mean, C_t, project_to_targets=True)
            predictions.append(y_pred)
            
            # Compute uncertainty with time-varying C matrix
            y_std = self._compute_observation_uncertainty(x_cov, C_t, R_diag, project_to_targets=True)
            uncertainties.append(y_std)
        
        # Stack results
        predictions = torch.stack(predictions, dim=-1)  # (batch, output_dim, time_steps)
        uncertainties = torch.stack(uncertainties, dim=-1)  # (batch, output_dim, time_steps)
        
        return predictions, uncertainties
    
    def predict_full_trajectory(self, control_inputs, historical_controls=None, historical_observations=None,
                disturbance_inputs=None, historical_disturbances=None, 
                matrix_generation_features=None, historical_matrix_generation_features=None, **kwargs):
        """
        Predict method that returns full trajectory including historical reconstruction.
        
        Override parent to use time-varying matrices A(d[t]), B(d[t]), C(d[t]), E(d[t])
        (for dynamic matrices).
        
        Args:
            control_inputs: Control inputs for prediction (batch, control_dim, time_steps)
            historical_controls: Historical controls (batch, control_dim, window)
            historical_observations: Historical observations (batch, output_dim, window)
            disturbance_inputs: Disturbance inputs for prediction (batch, disturbance_dim, time_steps)
                               Required if any matrix is piecewise
            historical_disturbances: Historical disturbances (batch, disturbance_dim, window)
                                    Required if any matrix is piecewise and using historical data
            matrix_generation_features: Alternative features for matrix generation during prediction 
                                       (batch, feature_dim, time_steps). If None, uses disturbance_inputs
            historical_matrix_generation_features: Alternative features for matrix generation during encoding
                                                  (batch, feature_dim, window). If None, uses historical_disturbances
            **kwargs: Additional model-specific parameters (unused, for interface compatibility)
            
        Returns:
            predictions_full: Predicted outputs (batch, output_dim, window + time_steps)
            uncertainties_full: Prediction uncertainties (batch, output_dim, window + time_steps)
            window_size: Number of timesteps in historical window
        """
        # Use matrix_generation_features if provided, else fall back to disturbance_inputs
        mgf = matrix_generation_features if matrix_generation_features is not None else disturbance_inputs
        hist_mgf = historical_matrix_generation_features if historical_matrix_generation_features is not None else historical_disturbances
        
        if len(self.dynamic_matrices) > 0 and mgf is None:
            raise ValueError(
                f"PWLKF with dynamic matrices {self.dynamic_matrices} requires "
                f"disturbance_inputs for prediction"
            )
        
        batch_size = control_inputs.shape[0]
        device = control_inputs.device
        window_size = historical_controls.shape[-1] if historical_controls is not None else 0
        
        # For all-static matrices, create dummy features for matrix generation
        if len(self.dynamic_matrices) == 0:
            time_steps = control_inputs.shape[-1]
            if mgf is None:
                mgf = torch.zeros(batch_size, 1, time_steps, device=device)
            if historical_controls is not None and hist_mgf is None:
                hist_mgf = torch.zeros(batch_size, 1, window_size, device=device)
        
        hist_predictions = []
        hist_uncertainties = []
        
        # Capture historical predictions by running encode step-by-step
        if historical_controls is not None and historical_observations is not None:
            if len(self.dynamic_matrices) > 0 and hist_mgf is None:
                raise ValueError(
                    f"PWLKF with dynamic matrices {self.dynamic_matrices} requires "
                    f"either historical_disturbances or historical_matrix_generation_features when using historical data"
                )
            
            # Initialize state with learnable P0
            x_mean = torch.zeros(batch_size, self.latent_dim, device=device)
            x_cov = self.kf.P0.unsqueeze(0).expand(batch_size, -1, -1).clone()
            
            # Pre-expand noise matrices (these are constant)
            R_expanded = self.R.unsqueeze(0).expand(batch_size, -1, -1)
            I_expanded = torch.eye(self.latent_dim, device=device).unsqueeze(0).expand(batch_size, -1, -1)
            R_diag = torch.diagonal(self.R, dim1=0, dim2=1).unsqueeze(0)
            
            # Sequential filtering through historical window
            for t in range(window_size):
                u_t = historical_controls[:, :, t]
                y_t = historical_observations[:, :, t]
                d_t = historical_disturbances[:, :, t] if historical_disturbances is not None else None
                mg_t = hist_mgf[:, :, t]
                
                # Generate time-varying matrices based on matrix generation features
                A_t, B_t, C_t, E_t = self._generate_matrices(mg_t)
                
                # Predict state with time-varying dynamics
                x_mean = self._compute_state_mean(x_mean, u_t, A_t, B_t, d_t, E_t)
                x_cov = self._compute_state_covariance(x_cov, A_t)
                
                # Compute predicted observation with time-varying C (project to targets for output)
                y_pred = self._compute_observation(x_mean, C_t, project_to_targets=True)
                
                # Compute uncertainty with time-varying C matrix
                y_std = self._compute_observation_uncertainty(x_cov, C_t, R_diag, project_to_targets=True)
                
                hist_predictions.append(y_pred)
                hist_uncertainties.append(y_std)
                
                # Update with measurement using time-varying C
                x_mean, x_cov = self.kf.update(x_mean, x_cov, y_t, C_t,
                                              C_expanded=C_t, R_expanded=R_expanded, I_expanded=I_expanded)
        else:
            # No historical data
            x_mean = torch.zeros(batch_size, self.latent_dim, device=device)
            x_cov = self.kf.P0.unsqueeze(0).expand(batch_size, -1, -1).clone()
        
        # Predict forward using time-varying matrices
        predictions, uncertainties = self.predict_with_kf(
            x_mean, x_cov, control_inputs, disturbance_inputs, 
            matrix_generation_features=mgf
        )
        
        # Concatenate historical and prediction phases
        if window_size > 0:
            hist_predictions = torch.stack(hist_predictions, dim=-1)
            hist_uncertainties = torch.stack(hist_uncertainties, dim=-1)
            
            predictions_full = torch.cat([hist_predictions, predictions], dim=-1)
            uncertainties_full = torch.cat([hist_uncertainties, uncertainties], dim=-1)
        else:
            predictions_full = predictions
            uncertainties_full = uncertainties
        
        return predictions_full, uncertainties_full, window_size


class PiecewiseBuildingDynamics(PWLKF):
    """
    Piecewise Linear Kalman Filter with building-specific physical constraints.
    
    Extends PWLKF with options to enforce physical constraints on the
    NN-generated state-space matrices, meaningful for building thermal models:
    - A diagonal: negative (thermal decay rates)
    - A off-diagonal: non-negative (thermal coupling between states)
    - B elements: positive (control heat transfer coefficients)
    - C elements: positive (sensor gains/thermal capacitances)
    - E elements: configurable sign constraints
    
    Key differences from BuildingDynamics (static LKF):
    - Constraints are applied to MLP outputs at each timestep
    - Matrices are functions of disturbances: A(d[t]), B(d[t]), etc.
    - More flexible: can mix constrained and unconstrained matrices
    
    Uses exponential parametrization to enforce positivity and sign constraints
    on the neural network outputs.
    """
    
    def __init__(
        self,
        control_features: list,
        disturbance_features: list = None,
        latent_dim: int = 3,
        observation_features: list = None,
        target_features: list = None,
        output_dim: int = 1,
        # Constraint flags
        positive_B: bool = True,
        positive_C: bool = True,
        constrained_A: bool = True,
        # PWLKF parameters
        process_noise_cov: float = 1e-3,
        measurement_noise_cov: float = 1e-2,
        learnable_noise: bool = True,
        noise_constraint_type: str = 'diagonal_positive',
        learning_rate: float = 1e-3,
        num_encoding_measurements: int = 1,
        nn_hidden_dims: list = None,
        nn_activation: str = 'relu',
        dynamic_matrices: list = None,
        **kwargs
    ):
        """
        Args:
            control_features: List of control input feature names
            disturbance_features: List of disturbance feature names (required for NN input)
            latent_dim: Dimension of latent state
            observation_features: List of measurement feature names
            target_features: List of target feature names
            output_dim: Dimension of observations/targets
            positive_B: If True, ensure all elements of B are positive (B = exp(MLP_B(d)))
            positive_C: If True, ensure all elements of C are positive (C = exp(MLP_C(d)))
            constrained_A: If True, constrain A to have negative diagonal and non-negative off-diagonal
            process_noise_cov: Initial process noise covariance
            measurement_noise_cov: Initial measurement noise covariance
            learnable_noise: If True, learn Q and R during training
            noise_constraint_type: Type of constraint for learnable noise covariances.
                                  Options: 'cholesky', 'diagonal_positive', 'none'
            learning_rate: Learning rate for optimizer
            num_encoding_measurements: Number of recent measurements to use for encoding
            nn_hidden_dims: Hidden layer dimensions for MLPs
            nn_activation: Activation function ('relu', 'tanh', 'elu')
            dynamic_matrices: List of matrix names to make piecewise linear
            **kwargs: Additional arguments passed to parent class
        """
        # Store constraint flags before calling parent
        self.positive_B = positive_B
        self.positive_C = positive_C
        self.constrained_A = constrained_A
        
        # Initialize parent class (creates MLPs for dynamic matrices)
        super().__init__(
            control_features=control_features,
            disturbance_features=disturbance_features,
            latent_dim=latent_dim,
            observation_features=observation_features,
            target_features=target_features,
            output_dim=output_dim,
            process_noise_cov=process_noise_cov,
            measurement_noise_cov=measurement_noise_cov,
            learnable_noise=learnable_noise,
            noise_constraint_type=noise_constraint_type,
            learning_rate=learning_rate,
            num_encoding_measurements=num_encoding_measurements,
            nn_hidden_dims=nn_hidden_dims,
            nn_activation=nn_activation,
            dynamic_matrices=dynamic_matrices,
            **kwargs
        )
        
        # Rebuild A generator if constrained and piecewise
        if constrained_A and 'A' in self.dynamic_matrices:
            self._rebuild_A_generator(nn_hidden_dims, nn_activation)
        
        # Initialize output biases for constrained matrices
        self._initialize_constrained_matrices()
        
        # Update hyperparameters
        self.save_hyperparameters()
    
    def _rebuild_A_generator(self, nn_hidden_dims, nn_activation):
        """
        Rebuild A matrix generator to output diagonal and off-diagonal separately.
        
        This allows us to apply different constraints to diagonal (negative)
        and off-diagonal (positive) elements.
        
        Args:
            nn_hidden_dims: Hidden layer dimensions
            nn_activation: Activation function name
        """
        # Get activation function
        activation_fn = {
            'relu': nn.ReLU,
            'tanh': nn.Tanh,
            'elu': nn.ELU
        }.get(nn_activation.lower(), nn.ReLU)
        
        # Output sizes: latent_dim for diagonal, latent_dim*(latent_dim-1) for off-diagonal
        diag_size = self.latent_dim
        offdiag_size = self.latent_dim * self.latent_dim - self.latent_dim
        total_output_size = diag_size + offdiag_size
        
        # Replace existing A generator with structured version
        mlp = self._build_mlp(
            input_dim=self.disturbance_dim,
            output_dim=total_output_size,
            hidden_dims=nn_hidden_dims if nn_hidden_dims else [2 * self.latent_dim] * 2,
            activation_fn=activation_fn
        )
        
        # CRITICAL: Initialize output layer bias to produce reasonable values after exp()
        # For diagonal: want -exp(x) ≈ -0.9 initially, so x = log(0.9) ≈ -0.1
        # For off-diagonal: want exp(x) ≈ 0.01 initially, so x = log(0.01) ≈ -4.6
        with torch.no_grad():
            output_layer = mlp[-1]  # Last layer
            # Initialize diagonal biases to log(0.9) for -exp(x) ≈ -0.9
            output_layer.bias[:diag_size] = torch.log(torch.tensor(0.9))
            # Initialize off-diagonal biases to log(0.01) for exp(x) ≈ 0.01 (small coupling)
            output_layer.bias[diag_size:] = torch.log(torch.tensor(0.01))
        
        self.matrix_generators['A'] = mlp
    
    def _initialize_constrained_matrices(self):
        """
        Initialize output layer biases for constrained matrices to produce reasonable
        initial values after exponential transformation.
        
        This is CRITICAL for training stability. Without proper initialization,
        exp(MLP_output) can produce extremely large or small values.
        
        Target initial values:
        - B: ~0.1 (small positive heat transfer coefficient) → bias = log(0.1) ≈ -2.3
        - C: ~1.0 (unity sensor gain) → bias = log(1.0) = 0
        - E: ~1.0 → bias = log(1.0) = 0
        """
        with torch.no_grad():
            # Initialize B (control matrix) - want small positive values initially
            if 'B' in self.matrix_generators and self.positive_B:
                output_layer = self.matrix_generators['B'][-1]
                # Target: B ≈ 0.1 initially (small heat transfer)
                output_layer.bias.fill_(torch.log(torch.tensor(0.1)).item())
            
            # Initialize C (observation matrix) - want values near 1 initially
            if 'C' in self.matrix_generators and self.positive_C:
                output_layer = self.matrix_generators['C'][-1]
                # Target: C ≈ 1.0 initially (unity gain)
                output_layer.bias.fill_(torch.log(torch.tensor(1.0)).item())  # log(1) = 0
            
            # Initialize E (disturbance matrix) - want small positive values if constrained
            if 'E' in self.matrix_generators:
                output_layer = self.matrix_generators['E'][-1]
                # Target: E ≈ 1.0 initially (small disturbance influence)
                output_layer.bias.fill_(torch.log(torch.tensor(1.0)).item())
    
    def _generate_constrained_A(self, d_t, batch_size):
        """
        Generate constrained A matrix with negative diagonal and positive off-diagonal.
        
        The MLP outputs [diag_params, offdiag_params] which are then transformed:
        - Diagonal: -exp(diag_params) → negative values
        - Off-diagonal: exp(offdiag_params) → positive values
        
        Args:
            d_t: Disturbances (batch_size, disturbance_dim)
            batch_size: Batch size
            
        Returns:
            A: State transition matrix (batch_size, latent_dim, latent_dim)
        """
        # Generate parameters from MLP
        A_params = self.matrix_generators['A'](d_t)  # (batch, diag_size + offdiag_size)
        
        # Split into diagonal and off-diagonal parameters
        diag_size = self.latent_dim
        A_diag_params = A_params[:, :diag_size]  # (batch, latent_dim)
        A_offdiag_params = A_params[:, diag_size:]  # (batch, latent_dim*(latent_dim-1))
        
        # Apply constraints using exponential parametrization
        A_diag = -torch.exp(A_diag_params)  # Negative diagonal (thermal decay)
        A_offdiag_flat = torch.exp(A_offdiag_params)  # Positive off-diagonal (coupling)
        
        # Reconstruct full A matrix
        # Create zero matrices and fill diagonal and off-diagonal separately
        A = torch.zeros(batch_size, self.latent_dim, self.latent_dim, device=d_t.device)
        
        # Set diagonal elements
        batch_indices = torch.arange(batch_size, device=d_t.device).unsqueeze(1)
        diag_indices = torch.arange(self.latent_dim, device=d_t.device).unsqueeze(0)
        A[batch_indices, diag_indices, diag_indices] = A_diag
        
        # Set off-diagonal elements
        # Create mask for off-diagonal positions
        mask = ~torch.eye(self.latent_dim, dtype=bool, device=d_t.device)
        mask_expanded = mask.unsqueeze(0).expand(batch_size, -1, -1)
        
        # Fill off-diagonal positions
        A[mask_expanded] = A_offdiag_flat.flatten()
        
        return A
    
    def _generate_matrices(self, d_t):
        """
        Generate state-space matrices from disturbances with physical constraints.
        
        Overrides parent method to apply building-specific constraints to MLP outputs:
        - A: constrained diagonal/off-diagonal structure if constrained_A=True
        - B: positive if positive_B=True
        - C: positive if positive_C=True
        
        Static matrices are simply replicated (constraints don't apply to them).
        
        Args:
            d_t: Disturbances at time t (batch_size, disturbance_dim)
            
        Returns:
            A: State transition matrix (batch_size, latent_dim, latent_dim)
            B: Control matrix (batch_size, latent_dim, control_dim)
            C: Observation matrix (batch_size, measurement_dim, latent_dim)
            E: Disturbance matrix (batch_size, latent_dim, disturbance_dim)
        """
        batch_size = d_t.shape[0]
        matrices = {}
        
        # Generate A with diagonal/off-diagonal constraints
        if 'A' in self.matrix_generators:
            if self.constrained_A:
                matrices['A'] = self._generate_constrained_A(d_t, batch_size)
            else:
                flat_A = self.matrix_generators['A'](d_t)
                matrices['A'] = flat_A.view(batch_size, self.latent_dim, self.latent_dim)
        else:
            # Static A matrix (replicate across batch)
            matrices['A'] = self.static_matrices['A'].unsqueeze(0).expand(batch_size, -1, -1)
        
        # Generate B with positivity constraint
        if 'B' in self.matrix_generators:
            flat_B = self.matrix_generators['B'](d_t)
            B = flat_B.view(batch_size, self.latent_dim, self.control_dim)
            if self.positive_B:
                B = torch.exp(B)  # Ensure positive (heat transfer coefficients)
            matrices['B'] = B
        else:
            # Static B matrix
            matrices['B'] = self.static_matrices['B'].unsqueeze(0).expand(batch_size, -1, -1)
        
        # Generate C with positivity constraint
        if 'C' in self.matrix_generators:
            flat_C = self.matrix_generators['C'](d_t)
            C = flat_C.view(batch_size, self.measurement_dim, self.latent_dim)
            if self.positive_C:
                C = torch.exp(C)  # Ensure positive (sensor gains)
            matrices['C'] = C
        else:
            # Static C matrix
            matrices['C'] = self.static_matrices['C'].unsqueeze(0).expand(batch_size, -1, -1)
        
        # Generate E
        if 'E' in self.matrix_generators:
            flat_E = self.matrix_generators['E'](d_t)
            E = flat_E.view(batch_size, self.latent_dim, self.disturbance_dim)
            matrices['E'] = E
        else:
            # Static E matrix
            matrices['E'] = self.static_matrices['E'].unsqueeze(0).expand(batch_size, -1, -1)
        
        return matrices['A'], matrices['B'], matrices['C'], matrices['E']
    
    