import copy

import numpy as np
import holidays
import pandas as pd
from pandas.tseries.frequencies import to_offset

TARGET = 'target'
LAGGED_TARGET = 'lagged_target'
TEMPERATURE = 'temp'
CONTROL = 'control'

# Temporal feature names
HOLIDAY = 'holiday'
WEEKDAY = 'weekday'
HOUR = 'hour'
MONTH = 'month'

def add_temporal_columns(df):
    fi_holidays = holidays.FI()  # todo support for other countries need to be added.
    df[HOLIDAY] = [int(x in fi_holidays) for x in df.index.date]
    df[WEEKDAY] = df.index.dayofweek
    df[HOUR] = df.index.hour
    df[MONTH] = df.index.month
    return df


def update_frequency_x(x_df, update_freq, start):
    # Modify X according to the update frequency.
    interval = to_offset(x_df.index[1] - x_df.index[0]) * update_freq
    x_df = x_df.resample(interval, closed='left', label='left', origin=start).first()

    # The resample above will create new rows if there are missing timesteps in the data (i.e., breaks in the data).
    # These new rows need to be removed as they are fully nan. Important: we don't want to remove all nan values
    # as those can be imbuted in the prepocessing pipeline, just the ones generated by the resample.
    # We will detect these values by checking whether temporal columns have nan values.

    # Form temporal columns in the x_df. The rows where those have nan valus will be dropped.
    prefixes_to_match = [HOUR, WEEKDAY, HOLIDAY]
    columns_to_dropna = []

    # Check if specified columns exist in the DataFrame
    for prefix in prefixes_to_match:
        columns_to_dropna.extend([col for col in x_df if prefix in col])

    # Remove rows with NaN values in specified columns if columns exist
    x_df = x_df.dropna(subset=columns_to_dropna)
    return x_df


def form_y(df, target, lead, flen, update_freq, start):
    """Forms Y columns to a dataframe by shifting target column according to the lead time and forecast length.

    Parameters
    ----------
    df: pd.DataFrame
        Input DataFrame containing the target column.
    target: str
        Name of the target column.
    lead: int
        Lead time (number of steps to shift the target forward).
    flen: int
        Forecast length (number of future steps to predict).
    update_freq: int
        Frequency for resampling the resulting DataFrame.
    start: str or pd.Timestamp
        Starting point for the resulting DataFrame.

    Returns
    -------
    pd.DataFrame
        DataFrame containing the shifted target values.
    """
    df = df.copy()  # Ensure the original DataFrame is not modified.

    # Generate all shifted columns at once
    y_columns = {f"y_{i}": df[target].shift(-i) for i in range(lead, lead + flen)}
    y_df = pd.concat(y_columns, axis=1)

    # Drop the rows from the end with no target.
    y_df = y_df.iloc[:len(df) - (lead + flen - 1)]

    # Modify Y according to the update frequency.
    interval = to_offset(y_df.index[1] - y_df.index[0]) * update_freq
    y_df = y_df.resample(interval, closed="left", label="left", origin=start).first()

    # Return the resampled DataFrame starting from `start`, dropping NaNs.
    return y_df.loc[start:].dropna()


def form_x_list(df_list, target, features=None, update_freq=1, start=None):
    """  Constructs X columns by shifting lagged and future input data so that they are in the same row.


    Parameters
    ----------
    df_list
    target
    features
    update_freq
    start

    Returns
    -------

    """
    df_list = copy.deepcopy(df_list)
    for df in df_list:
        df = add_temporal_columns(df)
        if LAGGED_TARGET in features.keys():
            df[LAGGED_TARGET] = df[target]

    samples = len(df_list)
    x_columns = []
    max_lag = 0
    max_future = 0
    new_cols = []

    # Create a multiindex DataFrame by concatenating the DataFrames and setting the first level of index
    # This is done to speed up the processing.
    joined_df = pd.concat(df_list, keys=list(range(len(df_list))), names=['DataFrame', 'Timestamp'])

    for label, f in features.items():
        for window in f['windows']:
            for i in range(window[0], window[1] + 1):   # Todo should this be 0, window[1] - window[0] + 1 not sure how this work with negatetive window?
                x_i = f'{label}_{i}'

                # Shift the values of the 'value' column for each group independently
                new_col = joined_df.groupby(level='DataFrame')[label].shift(-i).rename(x_i)
                new_cols.append(new_col)

                # In cases with overlapping feature windows there might be duplicate columns.
                # Only add unique columns
                if x_i not in x_columns:
                    x_columns.append(x_i)

                if (window[0] < 0) and (abs(window[0]) > max_lag):
                    max_lag = abs(window[0])
                if window[1] > max_future:
                    max_future = window[1]

    df = pd.concat(new_cols, axis=1)

    # Split the DF into separate DFs.
    df_list = [df.loc[i] for i in range(samples)]

    x_df_list = []
    for df in df_list:
        # Drop the rows from beginning with no input features. We don't drop all rows with nans because those
        # values are left to be processed (e.g. imbuted or dropped) with later layers of the pipeline.
        if max_future == 0:
            df = df.iloc[max_lag:]
        else:
            df = df.iloc[max_lag:-max_future]

        x_df = df[x_columns]

        if len(x_df) > 1:
            x_df = update_frequency_x(x_df, update_freq, start)

        x_df = x_df.astype('float32')
        x_df = x_df.loc[start:]
        x_df_list.append(x_df)

    return x_df_list


def form_x(df, target, features=None, update_freq=1, start=None):
    """ Constructs X columns by shifting lagged and future input data so that they are in the same row.

    Parameters
    ----------
    df
    target
    features
    update_freq
    start

    Returns
    -------

    """
    if features is None:
        return df

    df = df.copy()  # To not mess with the original df.
    df = add_temporal_columns(df)
    if LAGGED_TARGET in features.keys():
        df[LAGGED_TARGET] = df[target]

    x_columns = []
    max_lag = 0
    max_future = 0
    new_cols = []
    for label, f in features.items():
        for window in f['windows']:
            for i in range(window[0], window[1] + 1):   # Todo should this be 0, window[1] - window[0] + 1 not sure how this work with negatetive window?
                x_i = f'{label}_{i}'
                new_col = df[label].shift(-i).rename(x_i)
                new_cols.append(new_col)
                # In cases with overlapping feature windows there might be duplicate columns.
                # Only add unique columns
                if x_i not in x_columns:
                    x_columns.append(x_i)

                if (window[0] < 0) and (abs(window[0]) > max_lag):
                    max_lag = abs(window[0])
                if window[1] > max_future:
                    max_future = window[1]

    df = pd.concat(new_cols, axis=1)

    # Drop the rows from beginning with no input features. We don't drop all rows with nans because those
    # values are left to be processed (e.g. imbuted or dropped) with later layers of the pipeline.
    if max_future == 0:
        df = df.iloc[max_lag:]
    else:
        df = df.iloc[max_lag:-max_future]

    x_df = df[x_columns]

    if len(x_df) > 1:
        x_df = update_frequency_x(x_df, update_freq, start)
    x_df = x_df.astype('float32')
    return x_df.loc[start:]


def form_xy(df, target, lead, flen, features, update_freq=1, start=None):
    """  Creates columns for input features (X) and targets (Y).

    Data frames are shifted so that all input features and targets are in the same row. Timestamp of the row is the
    forecast time.

    Parameters
    ----------
    df
    target
    lead
    flen
    features
    update_freq
    start

    Returns
    -------

    """

    # Drop duplicate index
    df = df[~df.index.duplicated(keep='first')]

    y_df = form_y(df, target, lead, flen, update_freq, start)
    x_df = form_x(df, target, features, update_freq, start)

    y_df = y_df.loc[y_df.index.intersection(x_df.index)]
    x_df = x_df.loc[x_df.index.intersection(y_df.index)]

    return x_df, y_df


def sincos_transform(df, max_value):
    sine = np.sin(2 * np.pi * df.iloc[:, 0].values / max_value)
    cosine = np.cos(2 * np.pi * df.iloc[:, 0].values / max_value)
    sincos = np.stack([sine, cosine], axis=-1)
    return sincos


if __name__ == '__main__':
    np_arr = np.array([1, 2, 3])
    results = sincos_transform(np_arr, np_arr.max())
    print(results)

