"""
Piecewise Linear Kalman Filter with building-specific physical constraints.

Matrices A(d), B(d), C(d), E(d) are generated by small MLPs conditioned on current
disturbances, while satisfying the same physical constraints as BuildingDynamics:

  - A: off-diagonal ≥ 0, diagonal ∈ [offdiag_row_sum, 1], row_sum ≤ 1
       (discrete-time energy-conservation / stability constraint)
  - B: positive  (heat transfer coefficients)
  - C: positive (exp) or softmax, depending on constraint_C
  - E: positive  (disturbance influence coefficients)

Inherits directly from BuildingDynamics so:
  - Static (non-dynamic) matrices use BuildingDynamics' constrained parametrisation.
  - Dynamic matrices use an MLP output processed by the same BuildingDynamics
    static constraint helpers, guaranteeing identical physics between the two.
"""

import torch
import torch.nn as nn
from amp.torch.models.lkf import BuildingDynamics, BatchedLinearKalmanFilter


class BuildingPWLKF(BuildingDynamics):
    """
    Piecewise BuildingDynamics: MLP-generated, physically-constrained LKF matrices.

    Extends BuildingDynamics so that each matrix in `dynamic_matrices` is produced
    by a small MLP conditioned on the current disturbance vector d[t].  Matrices
    NOT in `dynamic_matrices` remain static and use the BuildingDynamics constrained
    parametrisation directly.

    Constraint rules (same as BuildingDynamics):
    - A:  off-diagonal ≥ 0, diagonal ∈ [offdiag_row_sum, 1] → row_sum ≤ 1
    - B:  positive (exp parametrisation)
    - C:  'positive' (exp) or 'softmax' — same as BuildingDynamics.constraint_C
    - E:  positive (exp parametrisation)
    """

    def __init__(
        self,
        control_features: list,
        disturbance_features: list = None,
        latent_dim: int = 3,
        observation_features: list = None,
        target_features: list = None,
        output_dim: int = 1,
        # Constraint flags — same semantics as BuildingDynamics
        positive_B: bool = True,
        constraint_C: str = 'positive',
        positive_E: bool = True,
        constrained_A: bool = True,
        # Piecewise (MLP) configuration
        dynamic_matrices: list = None,
        nn_hidden_dims: list = None,
        nn_activation: str = 'relu',
        # Kalman filter / training parameters
        process_noise_cov: float = 1e-3,
        measurement_noise_cov: float = 1e-2,
        learnable_noise: bool = True,
        noise_constraint_type: str = 'diagonal_positive',
        learning_rate: float = 1e-3,
        num_encoding_measurements: int = 1,
        **kwargs
    ):
        """
        Args:
            control_features: List of control input feature names.
            disturbance_features: List of disturbance feature names (required for dynamic matrices).
            latent_dim: Dimension of latent state.
            observation_features: List of measurement feature names.
            target_features: List of target feature names.
            output_dim: Dimension of observations/targets.
            positive_B: If True, B = exp(MLP_B(d)) — all elements positive.
            constraint_C: Constraint for C:
                          'positive' → C = exp(MLP_C(d)),
                          'softmax'  → row-wise softmax(MLP_C(d)),
                          None/other → unconstrained MLP output.
            positive_E: If True, E = exp(MLP_E(d)) — all elements positive.
            constrained_A: If True, enforce off-diagonal ≥ 0, diagonal ∈ [offdiag_sum, 1].
            dynamic_matrices: Which matrices are MLP-generated.  Default: all ['A','B','C','E'].
                              Matrices NOT in this list stay static (BuildingDynamics params).
            nn_hidden_dims: Hidden layer sizes for each MLP.  Default: [2*latent_dim, 2*latent_dim].
            nn_activation: Activation function ('relu', 'tanh', 'elu').
            process_noise_cov: Initial process noise covariance (Q).
            measurement_noise_cov: Initial measurement noise covariance (R).
            learnable_noise: If True, learn Q and R.
            noise_constraint_type: Constraint for learnable noise ('cholesky', 'diagonal_positive', 'none').
            learning_rate: Optimiser learning rate.
            num_encoding_measurements: How many past measurements to use for KF encoding
                                       (1 = last only, -1 = all, N = last N).
            **kwargs: Forwarded to BuildingDynamics (e.g. use_state_bias, n4sid_init, ...).
        """
        # ------------------------------------------------------------------
        # 1. Validate dynamic_matrices before anything else
        # ------------------------------------------------------------------
        if dynamic_matrices is None:
            dynamic_matrices = ['A', 'B', 'C', 'E']
        valid = {'A', 'B', 'C', 'E'}
        invalid = set(dynamic_matrices) - valid
        if invalid:
            raise ValueError(f"Invalid dynamic_matrices entries: {invalid}. Valid: {valid}")

        # ------------------------------------------------------------------
        # 2. Initialise BuildingDynamics — creates ALL static constrained params
        # ------------------------------------------------------------------
        # matrix_generation_features is handled by BuildingPWLKF itself (stored on self);
        # strip it from kwargs so it doesn't propagate to TorchLinearDynamicsWithKF.
        self.matrix_generation_features = kwargs.pop('matrix_generation_features', None) or []

        super().__init__(
            control_features=control_features,
            disturbance_features=disturbance_features,
            latent_dim=latent_dim,
            observation_features=observation_features,
            target_features=target_features,
            output_dim=output_dim,
            positive_B=positive_B,
            constraint_C=constraint_C,
            positive_E=positive_E,
            constrained_A=constrained_A,
            process_noise_cov=process_noise_cov,
            measurement_noise_cov=measurement_noise_cov,
            learnable_noise=learnable_noise,
            noise_constraint_type=noise_constraint_type,
            learning_rate=learning_rate,
            num_encoding_measurements=num_encoding_measurements,
            **kwargs
        )

        self.dynamic_matrices = dynamic_matrices

        if len(dynamic_matrices) > 0 and not self.has_disturbances:
            raise ValueError(
                f"BuildingPWLKF with dynamic matrices {dynamic_matrices} requires disturbance_features."
            )

        # ------------------------------------------------------------------
        # 3. Replace standard KF with batched variant (supports batch-varying C)
        # ------------------------------------------------------------------
        self.kf = BatchedLinearKalmanFilter(
            state_dim=latent_dim,
            input_dim=self.control_dim,
            output_dim=self.measurement_dim,
            process_noise_cov=process_noise_cov,
            measurement_noise_cov=measurement_noise_cov,
            learnable_noise=learnable_noise,
            noise_constraint_type=noise_constraint_type,
        )

        # ------------------------------------------------------------------
        # 4. Build MLPs for dynamic matrices; remove superseded static params
        # ------------------------------------------------------------------
        if nn_hidden_dims is None:
            nn_hidden_dims = [2 * latent_dim, 2 * latent_dim]
        activation_fn = {
            'relu': nn.ReLU, 'tanh': nn.Tanh, 'elu': nn.ELU,
        }.get((nn_activation or 'relu').lower(), nn.ReLU)

        self.nn_hidden_dims = nn_hidden_dims
        self.nn_activation = nn_activation

        offdiag_size = latent_dim * (latent_dim - 1)
        matrix_mlp_sizes = {
            # Constrained A outputs offdiag_params + diag_fraction_params
            'A': (offdiag_size + latent_dim) if constrained_A else (latent_dim * latent_dim),
            'B': latent_dim * self.control_dim,
            'C': self.measurement_dim * latent_dim,
            'E': latent_dim * self.disturbance_dim,
        }

        self.matrix_generators = nn.ModuleDict()
        for m in dynamic_matrices:
            self._remove_static_params_for(m)
            self.matrix_generators[m] = self._build_mlp(
                input_dim=self.disturbance_dim,
                output_dim=matrix_mlp_sizes[m],
                hidden_dims=nn_hidden_dims,
                activation_fn=activation_fn,
            )

        # ------------------------------------------------------------------
        # 5. Initialise MLP output biases for physically sensible start values
        # ------------------------------------------------------------------
        self._init_mlp_biases(offdiag_size)

        self.save_hyperparameters()

    # -----------------------------------------------------------------------
    # Initialisation helpers
    # -----------------------------------------------------------------------

    def _remove_static_params_for(self, matrix_name: str):
        """
        Delete the BuildingDynamics static parameters for *matrix_name*.

        This avoids wasted memory and prevents the optimiser from stepping
        parameters that never receive gradients.
        """
        if matrix_name == 'A':
            if self.constrained_A:
                for attr in ('log_A_offdiag', 'log_A_diag'):
                    if hasattr(self, attr):
                        delattr(self, attr)
            else:
                if 'A' in self._parameters:
                    delattr(self, 'A')
        elif matrix_name == 'B':
            for attr in ('log_B', '_B'):
                if hasattr(self, attr):
                    delattr(self, attr)
        elif matrix_name == 'C':
            for attr in ('log_C', '_C', '_C_identity'):
                if hasattr(self, attr):
                    delattr(self, attr)
        elif matrix_name == 'E':
            for attr in ('log_E', '_E'):
                if hasattr(self, attr):
                    delattr(self, attr)

    def _build_mlp(self, input_dim: int, output_dim: int,
                   hidden_dims: list, activation_fn) -> nn.Sequential:
        """Build a small MLP for matrix generation."""
        layers = []
        current = input_dim
        for h in hidden_dims:
            layers += [nn.Linear(current, h), activation_fn()]
            current = h
        layers.append(nn.Linear(current, output_dim))
        mlp = nn.Sequential(*layers)
        for layer in mlp:
            if isinstance(layer, nn.Linear):
                nn.init.xavier_uniform_(layer.weight, gain=0.1)
                nn.init.zeros_(layer.bias)
        return mlp

    def _init_mlp_biases(self, offdiag_size: int):
        """
        Set output-layer biases so that initial matrix values are physically
        sensible, matching BuildingDynamics initialisation targets.
        """
        with torch.no_grad():
            if 'A' in self.matrix_generators and self.constrained_A:
                bias = self.matrix_generators['A'][-1].bias
                bias[:offdiag_size] = torch.log(torch.tensor(0.01))  # small off-diagonal
                bias[offdiag_size:] = 0.0                             # sigmoid(0) = 0.5

            if 'B' in self.matrix_generators and self.positive_B:
                self.matrix_generators['B'][-1].bias.fill_(
                    torch.log(torch.tensor(0.1)).item()               # exp(-2.3) ≈ 0.1
                )

            if 'C' in self.matrix_generators and self.constraint_C == 'positive':
                self.matrix_generators['C'][-1].bias.fill_(0.0)      # exp(0) = 1

            if 'E' in self.matrix_generators and self.positive_E:
                self.matrix_generators['E'][-1].bias.fill_(0.0)      # exp(0) = 1

    # -----------------------------------------------------------------------
    # Matrix generation
    # -----------------------------------------------------------------------

    def _generate_constrained_A(self, d_t, batch_size):
        """
        Generate batched A from MLP output via BuildingDynamics._apply_A_constraint.
        """
        offdiag_size = self.latent_dim * (self.latent_dim - 1)
        params = self.matrix_generators['A'](d_t)
        return BuildingDynamics._apply_A_constraint(
            params[:, :offdiag_size], params[:, offdiag_size:], self.latent_dim, d_t.device
        )

    def _generate_matrices(self, d_t):
        """
        Return A, B, C, E at time t as batched (batch, rows, cols) tensors.

        Dynamic matrices: MLP(d_t) → BuildingDynamics constraint helper.
        Static matrices:  BuildingDynamics property (constrained static param).

        Args:
            d_t: Current disturbances (batch, disturbance_dim)

        Returns:
            A: (batch, latent_dim, latent_dim)
            B: (batch, latent_dim, control_dim)
            C: (batch, measurement_dim, latent_dim)
            E: (batch, latent_dim, disturbance_dim)
        """
        batch_size = d_t.shape[0]
        matrices = {}

        # A
        if 'A' in self.matrix_generators:
            if self.constrained_A:
                matrices['A'] = self._generate_constrained_A(d_t, batch_size)
            else:
                matrices['A'] = self.matrix_generators['A'](d_t).view(
                    batch_size, self.latent_dim, self.latent_dim)
        else:
            matrices['A'] = self.A.unsqueeze(0).expand(batch_size, -1, -1)

        # B
        if 'B' in self.matrix_generators:
            raw = self.matrix_generators['B'](d_t).view(
                batch_size, self.latent_dim, self.control_dim)
            matrices['B'] = BuildingDynamics._apply_B_constraint(raw) if self.positive_B else raw
        else:
            matrices['B'] = self.B.unsqueeze(0).expand(batch_size, -1, -1)

        # C
        if 'C' in self.matrix_generators:
            raw = self.matrix_generators['C'](d_t).view(
                batch_size, self.measurement_dim, self.latent_dim)
            if self.constraint_C in ('positive', 'softmax'):
                matrices['C'] = BuildingDynamics._apply_C_constraint(raw, self.constraint_C)
            else:
                matrices['C'] = raw
        else:
            matrices['C'] = self.C.unsqueeze(0).expand(batch_size, -1, -1)

        # E
        if 'E' in self.matrix_generators:
            raw = self.matrix_generators['E'](d_t).view(
                batch_size, self.latent_dim, self.disturbance_dim)
            matrices['E'] = BuildingDynamics._apply_E_constraint(raw) if self.positive_E else raw
        else:
            E = self.E  # None when has_disturbances=False
            matrices['E'] = E.unsqueeze(0).expand(batch_size, -1, -1) if E is not None else None

        return matrices['A'], matrices['B'], matrices['C'], matrices['E']

    # -----------------------------------------------------------------------
    # Batched compute overrides
    # Matrices are 3-D (batch, rows, cols) so standard @ matmul is used.
    # -----------------------------------------------------------------------

    def _compute_state_mean(self, x_mean, u_t, A, B, d_t=None, E=None):
        """x[t+1] = A @ x[t] + B @ u[t] + E @ d[t] + b_x  (batched matrices)."""
        x_next = (A @ x_mean.unsqueeze(-1)).squeeze(-1)
        x_next = x_next + (B @ u_t.unsqueeze(-1)).squeeze(-1)
        if d_t is not None and E is not None:
            x_next = x_next + (E @ d_t.unsqueeze(-1)).squeeze(-1)
        return x_next + self.b_x

    def _compute_state_covariance(self, x_cov, A):
        """P[t+1] = A @ P[t] @ A.T + Q  (batched A)."""
        return A @ x_cov @ A.transpose(-2, -1) + self.Q.unsqueeze(0)

    def _compute_observation(self, x_mean, C, project_to_targets=False):
        """y = C @ x + b_y  (batched C passed explicitly)."""
        y = (C @ x_mean.unsqueeze(-1)).squeeze(-1) + self.b_y
        if project_to_targets and self.target_indices is not None:
            y = y[:, self.target_indices]
        return y

    def _compute_observation_uncertainty(self, x_cov, C, R_diag, project_to_targets=False):
        """std(y) = sqrt(diag(C @ P @ C.T) + R_diag)  (batched C)."""
        C_x_cov = C @ x_cov                                  # (batch, meas, latent)
        y_var = (C_x_cov * C).sum(dim=-1) + R_diag           # (batch, meas)
        if project_to_targets and self.target_indices is not None:
            y_var = y_var[:, self.target_indices]
        return torch.sqrt(y_var)

    # -----------------------------------------------------------------------
    # KF loop overrides
    # -----------------------------------------------------------------------

    def encode_with_kf(self, control_inputs, measurements, disturbance_inputs=None,
                       matrix_generation_features=None, **kwargs):
        """
        Encode initial state using KF predict-update cycles with time-varying matrices.

        Args:
            control_inputs:  (batch, control_dim, window)
            measurements:    (batch, meas_dim, window)
            disturbance_inputs: (batch, disturbance_dim, window)
            matrix_generation_features: alternative MLP input; defaults to disturbance_inputs.

        Returns:
            x_mean_traj: (batch, latent_dim, steps)
            x_cov_traj:  (batch, latent_dim, latent_dim, steps)
        """
        mgf = matrix_generation_features if matrix_generation_features is not None else disturbance_inputs
        if len(self.dynamic_matrices) > 0 and mgf is None:
            raise ValueError(
                f"BuildingPWLKF with dynamic matrices {self.dynamic_matrices} requires "
                f"disturbance_inputs or matrix_generation_features for encode_with_kf."
            )

        batch_size = control_inputs.shape[0]
        window_size = control_inputs.shape[-1]
        device = control_inputs.device

        x_mean = torch.zeros(batch_size, self.latent_dim, device=device)
        x_cov = self.kf.P0.unsqueeze(0).expand(batch_size, -1, -1).clone()
        x_mean_traj, x_cov_traj = [], []

        R_expanded = self.R.unsqueeze(0).expand(batch_size, -1, -1)
        I_expanded = torch.eye(self.latent_dim, device=device).unsqueeze(0).expand(batch_size, -1, -1)

        if len(self.dynamic_matrices) == 0 and mgf is None:
            mgf = torch.zeros(batch_size, 1, window_size, device=device)

        if self.num_encoding_measurements == 1:
            # Fastest: KF update from the last measurement only
            _, _, C_last, _ = self._generate_matrices(mgf[:, :, -1])
            x_mean, x_cov = self.kf.update(
                x_mean, x_cov, measurements[:, :, -1], C_last,
                C_expanded=C_last, R_expanded=R_expanded, I_expanded=I_expanded)
            x_mean_traj.append(x_mean)
            x_cov_traj.append(x_cov)

        elif self.num_encoding_measurements == -1:
            # Full sequential KF over the entire window
            for t in range(window_size):
                u_t = control_inputs[:, :, t]
                y_t = measurements[:, :, t]
                d_t = disturbance_inputs[:, :, t] if disturbance_inputs is not None else None
                A_t, B_t, C_t, E_t = self._generate_matrices(mgf[:, :, t])
                x_mean = self._compute_state_mean(x_mean, u_t, A_t, B_t, d_t, E_t)
                x_cov = self._compute_state_covariance(x_cov, A_t)
                x_mean, x_cov = self.kf.update(
                    x_mean, x_cov, y_t, C_t,
                    C_expanded=C_t, R_expanded=R_expanded, I_expanded=I_expanded)
                x_mean_traj.append(x_mean)
                x_cov_traj.append(x_cov)

        else:
            # Partial: KF over the last N measurements
            num_steps = min(self.num_encoding_measurements, window_size)
            for t in range(window_size - num_steps, window_size):
                u_t = control_inputs[:, :, t]
                y_t = measurements[:, :, t]
                d_t = disturbance_inputs[:, :, t] if disturbance_inputs is not None else None
                A_t, B_t, C_t, E_t = self._generate_matrices(mgf[:, :, t])
                x_mean = self._compute_state_mean(x_mean, u_t, A_t, B_t, d_t, E_t)
                x_cov = self._compute_state_covariance(x_cov, A_t)
                x_mean, x_cov = self.kf.update(
                    x_mean, x_cov, y_t, C_t,
                    C_expanded=C_t, R_expanded=R_expanded, I_expanded=I_expanded)
                x_mean_traj.append(x_mean)
                x_cov_traj.append(x_cov)

        return torch.stack(x_mean_traj, dim=-1), torch.stack(x_cov_traj, dim=-1)

    def predict_with_kf(self, x_mean, x_cov, control_inputs, disturbance_inputs=None,
                        matrix_generation_features=None, **kwargs):
        """
        Predict future outputs using time-varying matrices from the MLPs.

        Args:
            x_mean: (batch, latent_dim)
            x_cov:  (batch, latent_dim, latent_dim)
            control_inputs: (batch, control_dim, time_steps)
            disturbance_inputs: (batch, disturbance_dim, time_steps)
            matrix_generation_features: alternative MLP input

        Returns:
            predictions:   (batch, output_dim, time_steps)
            uncertainties: (batch, output_dim, time_steps)
        """
        mgf = matrix_generation_features if matrix_generation_features is not None else disturbance_inputs
        if len(self.dynamic_matrices) > 0 and mgf is None:
            raise ValueError(
                f"BuildingPWLKF with dynamic matrices {self.dynamic_matrices} requires "
                f"disturbance_inputs or matrix_generation_features for predict_with_kf."
            )

        batch_size = control_inputs.shape[0]
        time_steps = control_inputs.shape[-1]
        device = control_inputs.device

        if len(self.dynamic_matrices) == 0 and mgf is None:
            mgf = torch.zeros(batch_size, 1, time_steps, device=device)

        R_diag = torch.diagonal(self.R, dim1=0, dim2=1).unsqueeze(0)
        predictions, uncertainties = [], []

        for t in range(time_steps):
            u_t = control_inputs[:, :, t]
            d_t = disturbance_inputs[:, :, t] if disturbance_inputs is not None else None
            A_t, B_t, C_t, E_t = self._generate_matrices(mgf[:, :, t])
            x_mean = self._compute_state_mean(x_mean, u_t, A_t, B_t, d_t, E_t)
            x_cov = self._compute_state_covariance(x_cov, A_t)
            predictions.append(self._compute_observation(x_mean, C_t, project_to_targets=True))
            uncertainties.append(
                self._compute_observation_uncertainty(x_cov, C_t, R_diag, project_to_targets=True)
            )

        return torch.stack(predictions, dim=-1), torch.stack(uncertainties, dim=-1)

    def predict_full_trajectory(self, control_inputs, historical_controls=None,
                                historical_observations=None, disturbance_inputs=None,
                                historical_disturbances=None,
                                matrix_generation_features=None,
                                historical_matrix_generation_features=None,
                                **kwargs):
        """
        Predict full trajectory: historical reconstruction + forecast.

        Historical filter outputs are concatenated with forecast outputs so
        downstream code receives a continuous output series.

        Args:
            control_inputs: (batch, control_dim, time_steps)
            historical_controls: (batch, control_dim, window)
            historical_observations: (batch, meas_dim, window)
            disturbance_inputs: (batch, disturbance_dim, time_steps)
            historical_disturbances: (batch, disturbance_dim, window)
            matrix_generation_features: MLP input for forecast phase
            historical_matrix_generation_features: MLP input for encoding phase

        Returns:
            predictions_full:   (batch, output_dim, window + time_steps)
            uncertainties_full: (batch, output_dim, window + time_steps)
            window_size: int
        """
        mgf = matrix_generation_features if matrix_generation_features is not None else disturbance_inputs
        hist_mgf = (historical_matrix_generation_features
                    if historical_matrix_generation_features is not None
                    else historical_disturbances)

        if len(self.dynamic_matrices) > 0 and mgf is None:
            raise ValueError(
                f"BuildingPWLKF with dynamic matrices {self.dynamic_matrices} requires "
                f"disturbance_inputs for prediction."
            )

        batch_size = control_inputs.shape[0]
        device = control_inputs.device
        window_size = historical_controls.shape[-1] if historical_controls is not None else 0

        if len(self.dynamic_matrices) == 0:
            t_steps = control_inputs.shape[-1]
            if mgf is None:
                mgf = torch.zeros(batch_size, 1, t_steps, device=device)
            if historical_controls is not None and hist_mgf is None:
                hist_mgf = torch.zeros(batch_size, 1, window_size, device=device)

        hist_preds, hist_unc = [], []

        if historical_controls is not None and historical_observations is not None:
            if len(self.dynamic_matrices) > 0 and hist_mgf is None:
                raise ValueError(
                    f"BuildingPWLKF with dynamic matrices {self.dynamic_matrices} requires "
                    f"historical_disturbances or historical_matrix_generation_features."
                )

            x_mean = torch.zeros(batch_size, self.latent_dim, device=device)
            x_cov = self.kf.P0.unsqueeze(0).expand(batch_size, -1, -1).clone()
            R_expanded = self.R.unsqueeze(0).expand(batch_size, -1, -1)
            I_expanded = torch.eye(self.latent_dim, device=device).unsqueeze(0).expand(batch_size, -1, -1)
            R_diag = torch.diagonal(self.R, dim1=0, dim2=1).unsqueeze(0)

            for t in range(window_size):
                u_t = historical_controls[:, :, t]
                y_t = historical_observations[:, :, t]
                d_t = historical_disturbances[:, :, t] if historical_disturbances is not None else None
                A_t, B_t, C_t, E_t = self._generate_matrices(hist_mgf[:, :, t])
                x_mean = self._compute_state_mean(x_mean, u_t, A_t, B_t, d_t, E_t)
                x_cov = self._compute_state_covariance(x_cov, A_t)
                hist_preds.append(self._compute_observation(x_mean, C_t, project_to_targets=True))
                hist_unc.append(
                    self._compute_observation_uncertainty(x_cov, C_t, R_diag, project_to_targets=True)
                )
                x_mean, x_cov = self.kf.update(
                    x_mean, x_cov, y_t, C_t,
                    C_expanded=C_t, R_expanded=R_expanded, I_expanded=I_expanded)
        else:
            x_mean = torch.zeros(batch_size, self.latent_dim, device=device)
            x_cov = self.kf.P0.unsqueeze(0).expand(batch_size, -1, -1).clone()

        predictions, uncertainties = self.predict_with_kf(
            x_mean, x_cov, control_inputs, disturbance_inputs,
            matrix_generation_features=mgf
        )

        if window_size > 0:
            predictions_full = torch.cat([torch.stack(hist_preds, dim=-1), predictions], dim=-1)
            uncertainties_full = torch.cat([torch.stack(hist_unc, dim=-1), uncertainties], dim=-1)
        else:
            predictions_full = predictions
            uncertainties_full = uncertainties

        return predictions_full, uncertainties_full, window_size

    def print_learned_matrices(self):
        """
        Print learned matrices. For dynamic (MLP-generated) matrices, evaluates the MLP
        at a nominal zero disturbance (d=0) to give a useful snapshot of the learned values.
        Static matrices are printed directly from their constrained parameters.
        """
        import torch

        print("\n" + "=" * 80)
        print("LEARNED STATE-SPACE MATRICES AND PARAMETERS")
        print("=" * 80)

        print(f"\nModel Dimensions:")
        print(f"  Latent state dimension: {self.latent_dim}")
        print(f"  Control dimension: {self.control_dim}")
        print(f"  Disturbance dimension: {self.disturbance_dim}")
        print(f"  Observation dimension: {self.measurement_dim}")
        print(f"  Output dimension: {self.output_dim}")

        print(f"\nFeature Names:")
        print(f"  Control features: {self.control_features}")
        print(f"  Disturbance features: {self.disturbance_features}")
        if self.observation_features:
            print(f"  Observation features: {self.observation_features}")
        if self.target_features:
            print(f"  Target features: {self.target_features}")

        print(f"\nDynamic matrices (MLP-generated at d=0): {self.dynamic_matrices}")
        print(f"Static matrices: {[m for m in ['A', 'B', 'C', 'E'] if m not in self.dynamic_matrices]}")

        # Evaluate all matrices at nominal d=0
        device = next(self.parameters()).device
        with torch.no_grad():
            d_nominal = torch.zeros(1, self.disturbance_dim, device=device)
            A, B, C, E = self._generate_matrices(d_nominal)
            # Squeeze batch dim
            A = A[0]; B = B[0]; C = C[0]
            E = E[0] if E is not None else None

        def _print_matrix(name, mat, row_labels=None, col_labels=None):
            print(f"\n{'=' * 80}")
            label = f" (MLP @ d=0)" if name in self.dynamic_matrices else " (static)"
            print(f"{name} Matrix{label}: shape {list(mat.shape)}")
            print("=" * 80)
            with torch.no_grad():
                np_mat = mat.cpu().numpy()
            rows, cols = np_mat.shape
            for i in range(rows):
                row_label = f"  {row_labels[i]:30s}: " if row_labels else "  "
                row_str = row_label + "  ".join([f"{v:8.4f}" for v in np_mat[i]])
                print(row_str)

        _print_matrix("A", A)
        _print_matrix("B", B, col_labels=self.control_features)
        obs_labels = self.observation_features if self.observation_features else None
        _print_matrix("C", C, row_labels=obs_labels)
        if E is not None:
            _print_matrix("E", E)

        if self.use_state_bias:
            print(f"\n{'=' * 80}")
            print(f"b_x (State Bias): shape {list(self.b_x.shape)}")
            print("=" * 80)
            with torch.no_grad():
                print("  " + "  ".join([f"{v:8.4f}" for v in self.b_x.cpu().numpy()]))

        if self.use_observation_bias:
            print(f"\n{'=' * 80}")
            print(f"b_y (Observation Bias): shape {list(self.b_y.shape)}")
            print("=" * 80)
            with torch.no_grad():
                b_y_np = self.b_y.cpu().numpy()
            for i, val in enumerate(b_y_np):
                obs_name = (self.observation_features[i]
                            if self.observation_features else f"Obs_{i+1}")
                print(f"  {obs_name}: {val:8.4f}")

        print(f"\n{'=' * 80}")
        print("Q Matrix (Process Noise Covariance):")
        print("=" * 80)
        with torch.no_grad():
            Q_np = self.Q.cpu().numpy()
        for i in range(self.latent_dim):
            print(f"  State_{i+1}: {Q_np[i, i]:8.6f}")

        print(f"\n{'=' * 80}")
        print("R Matrix (Measurement Noise Covariance):")
        print("=" * 80)
        with torch.no_grad():
            R_np = self.R.cpu().numpy()
        for i in range(self.measurement_dim):
            obs_name = (self.observation_features[i]
                        if self.observation_features else f"Obs_{i+1}")
            print(f"  {obs_name}: {R_np[i, i]:8.6f}")

        print("\n" + "=" * 80)
        print("END OF LEARNED MATRICES")
        print("=" * 80 + "\n")